Vagrant.configure(2) do |config|
  config.vm.box = "centos70"

  config.vm.define "web" do |web|
    web.vm.network "forwarded_port", guest: 80, host: 8080
    web.vm.network "private_network", ip: "192.168.33.10"
  end

  config.vm.define "aggregator" do |aggregator|
    aggregator.vm.network "private_network", ip: "192.168.33.11"
  end

  config.vm.define "log" do |log|
    log.vm.network "private_network", ip: "192.168.33.12"
  end

end
